### ISSUE TITLE
Fix - Remove light green cover from website

### ISSUE THREAD

**Issue by frankiefab100** [frankiefab100/Blockchain-Development-Resources#29]
On visiting the repository docs website, the first section is a light green cover of the css classname `section.cover.show`.
Adjust the css style so this section doesn't show. See screenshot below:

![Blockchain-Development-Resources](https://github.com/frankiefab100/Blockchain-Development-Resources/assets/46662771/0ad26406-3c28-4d83-8952-09b47a446927)

**Comment by Akash1965** [comment]
Hi @frankiefab100 I have resolved your issue.
Please do give it a look.
Hope you'll like it

**Comment by frankiefab100** [comment]
Thank you for the contribution @Akash1965
